"""Task #5: replace the pooled regime table (S3) with FULLY GRANULAR per-cell tables.

One row per (dataset, backbone, cap) -- averaging over the 4 seeds ONLY, never pooling
across backbones or caps. Two paired comparisons per row:
  * cc-F1  vs the best constraint-TRAINED baseline (per-seed max of Fioretto/Hounie),
  * macro-F1 vs the best POST-HOC clipper   (per-seed max of Heuristic/LP-LG).
Gaps are paired by seed then averaged; 'win' is the seed-winrate (k/4).

Emits, into paper/tables/:
  tab_granular_tissue.tex, tab_granular_derm.tex, tab_granular_oct.tex  (symmetric grid)
  tab_granular_asym.tex   (MobileNetV3 asymmetric caps: DermMNIST + TissueMNIST)

Symmetric data = sweep 'paper_final' (3 bb x 9 caps). Asymmetric = the dedicated
MobileNetV3 sweeps in the corpus (derm=paperv2_phase2, tissue=g2_asym_tissue_aider).

Run:  python paper/scripts/make_granular_tables.py
"""
import os
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV = os.path.join(ROOT, "data", "corpus", "corpus_final.csv")
TABLES = os.path.join(ROOT, "tables")
DUALS = ["fioretto_ldf", "hounie_rcl"]
CLIP = ["heuristic", "danits_lp"]
SYM_TAGS = [f"L{p}0_G{p}0" for p in range(1, 10)]  # L10..L90
BB_ORDER = [("MobileNetV3", "MobileNetV3"), ("RegNetY400MF", "RegNetY-400MF"),
            ("ViTB16", "ViT-B/16")]


def cell_stats(sub):
    """sub = rows for one (dataset, model, cap). Returns paired cc + macro stats."""
    cc = sub.pivot_table(index="seed", columns="method", values="cc_f1")
    mac = sub.pivot_table(index="seed", columns="method", values="f1_macro")
    have_tr = "tralo" in cc and cc["tralo"].notna().any()
    if not have_tr:
        return None
    r = {}
    # cc-F1 vs best trained dual
    duals = [d for d in DUALS if d in cc]
    if duals:
        best_tr = cc[duals].max(axis=1)
        pair = pd.concat([cc["tralo"], best_tr], axis=1, keys=["tralo", "best"]).dropna()
        r["cc_best"] = pair["best"].mean()
        r["cc_tralo"] = pair["tralo"].mean()
        r["cc_delta"] = (pair["tralo"] - pair["best"]).mean()
        r["cc_win"] = int((pair["tralo"] > pair["best"]).sum())
        r["cc_n"] = len(pair)
    # macro-F1 vs best clipper
    clips = [c for c in CLIP if c in mac]
    if clips:
        best_cl = mac[clips].max(axis=1)
        pair = pd.concat([mac["tralo"], best_cl], axis=1, keys=["tralo", "best"]).dropna()
        r["mac_delta"] = (pair["tralo"] - pair["best"]).mean()
    return r


def fmt_delta(x, bold_win=False):
    """Deltas in units of 1e-3, as signed integers.

    A column of '+0.002 / -0.005 / +0.013' is unreadable at a glance: the shared
    '0.00' prefix carries no information and swamps the digit that does. Rendering
    the same numbers as '+2 / -5 / +13' loses nothing and scans instantly.
    """
    if x is None or np.isnan(x):
        return "--"
    m = x * 1000
    # One decimal, not zero: with integer milli-units a raw +0.0046 prints as '+5'
    # and would then read as clearing the +5 win bar that it actually misses. One
    # decimal keeps the printed number sufficient to check the verdict against.
    s = "0.0" if abs(m) < 0.05 else f"{m:+.1f}"
    return f"\\textbf{{{s}}}" if bold_win else s


def outcome(delta, win, n):
    """Per-cell verdict under the paper's own win rule, applied symmetrically.

    Without this the reader must decide for themselves whether '-0.005 (1/4)' is a
    loss or noise, and the eye defaults to 'loss'. Naming the tie band explicitly is
    both more readable and more accurate: most of this grid is a genuine tie.
    """
    if delta is None or np.isnan(delta):
        return "--"
    # Threshold the RAW value, exactly as the original table did, so that no cell
    # changes verdict as a side effect of reformatting. The printed value carries a
    # decimal precisely so it stays sufficient to verify this rule.
    strong = n and (win / n) >= 0.75
    strong_against = n and ((n - win) / n) >= 0.75
    if delta >= 0.005 and strong:
        return "win"
    if delta <= -0.005 and strong_against:
        return "loss"
    return "tie"


def block_summary(rows):
    """'9 cells: 1 win / 8 tie / 0 loss, median +2' for one backbone block."""
    if not rows:
        return ""
    w = sum(1 for r in rows if r == "win")
    t = sum(1 for r in rows if r == "tie")
    l = sum(1 for r in rows if r == "loss")
    # Kept terse on purpose: this sits in an unwrappable \multicolumn row, so a long
    # tally here silently sets the whole table's minimum width and overruns the column.
    return f"{len(rows)} cells: {w}W / {t}T / {l}L"


def sym_table(df, dataset, title, label):
    d = df[(df.sweep == "paper_final") & (df.dataset == dataset)]
    lines = [
        "% AUTO-GENERATED by scripts/make_granular_tables.py -- do not hand-edit.",
        # [tp], and declared early (see supplementary.tex): these must be allowed to
        # share a page with body text. Under [p] they land on float-only pages, which
        # cannot carry the bibliography text that would otherwise fill the leftover
        # column, so a whole column comes out blank.
        # NB: do not reach for \footnotesize to shrink them -- aaai2027.sty redefines
        # \footnotesize to 9pt, identical to \small, so it is a no-op in this class.
        "\\begin{table}[tp]\\centering\\small",
        "\\setlength{\\tabcolsep}{3pt}",
        f"\\caption{{\\textbf{{{title}: per-cell constrained-class and overall F1.}} "
        "One row per (backbone, cap), mean over seeds $1$--$4$. cc-F1 columns compare TraLO "
        "to the best constraint-trained baseline (per-seed best of Fioretto-LDF/Hounie-RCL, "
        "paired); \\emph{win} is the seed-winrate. $\\Delta$mac is TraLO minus the best "
        "post-hoc clipper on macro-F1. \\textbf{All $\\Delta$ are in units of $10^{-3}$} "
        "(so $+13.4$ means $+0.0134$ F1). Each cell is scored \\emph{win} "
        "($\\Delta\\ge{+}5$ on $\\ge3/4$ seeds), \\emph{loss} (the mirror image), or "
        "\\emph{tie}; the per-backbone tally is given in each block header. Read this "
        "table for the \\emph{pattern}, not the individual cells: on the constrained "
        "class it is overwhelmingly ties, which is the honest result, while $\\Delta$mac "
        "stays positive nearly everywhere: the constraint-trained family is better "
        "\\emph{overall} than post-hoc clipping even where it merely ties on the "
        "constrained class.}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{l rr r c l r}",
        "\\toprule",
        " & \\multicolumn{5}{c}{cc-F1 vs.\\ best trained} & macro \\\\",
        "\\cmidrule(lr){2-6}\\cmidrule(lr){7-7}",
        "Cap & best & TraLO & $\\Delta$ & win & & $\\Delta$mac \\\\",
        "\\midrule",
    ]
    for mkey, mlab in BB_ORDER:
        dm = d[d.model == mkey]
        if dm.empty:
            continue
        blk, verdicts = [], []
        for tag in SYM_TAGS:
            sub = dm[dm.constraint_tag == tag]
            if sub.empty:
                continue
            r = cell_stats(sub)
            if r is None:
                continue
            cap = tag.split("_")[0]
            win = r.get("cc_win", 0)
            n = r.get("cc_n", 4)
            delta = r.get("cc_delta")
            verd = outcome(delta, win, n)
            verdicts.append(verd)
            blk.append(
                f"{cap} & {r.get('cc_best', float('nan')):.3f} & {r.get('cc_tralo', float('nan')):.3f} & "
                f"{fmt_delta(delta, verd == 'win')} & {win}/{n} & {verd} & "
                f"{fmt_delta(r.get('mac_delta'))} \\\\")
        if not blk:
            continue
        lines.append(f"\\multicolumn{{7}}{{l}}{{\\textit{{{mlab}}}\\quad"
                     f"\\footnotesize {block_summary(verdicts)}}} \\\\")
        lines.extend(blk)
        lines.append("\\addlinespace[2pt]")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    out = os.path.join(TABLES, label.replace("tab:", "tab_") + ".tex")
    fname = {"tab:gran_tissue": "tab_granular_tissue.tex",
             "tab:gran_derm": "tab_granular_derm.tex",
             "tab:gran_oct": "tab_granular_oct.tex"}[label]
    with open(os.path.join(TABLES, fname), "w") as f:
        f.write("\n".join(lines))
    return fname


def asym_table(df):
    specs = [("dermmnist", "paperv2_phase2", "DermMNIST"),
             ("tissuemnist", "g2_asym_tissue_aider", "TissueMNIST")]
    lines = [
        "% AUTO-GENERATED by scripts/make_granular_tables.py -- do not hand-edit.",
        "\\begin{table}[p]\\centering\\small",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\caption{\\textbf{Asymmetric caps (MobileNetV3): per-cell F1.} Group cap $L$ and "
        "global cap $G$ set independently; one row per cap pair, mean over seeds $1$--$4$. "
        "Columns, $10^{-3}$ units, and the win/tie/loss rule are as in "
        "Table~\\ref{tab:gran_derm}. The contrast between the two DermMNIST blocks is the "
        "point: the preliminary cc-F1 win sits in the global-tighter ($G{<}L$) block and "
        "vanishes when the local cap binds instead ($G{>}L$), which is the regime "
        "dependence the main paper reports; $\\Delta$mac stays positive throughout.}",
        "\\label{tab:gran_asym}",
        "\\begin{tabular}{l rr r c l r}",
        "\\toprule",
        " & \\multicolumn{5}{c}{cc-F1 vs.\\ best trained} & macro \\\\",
        "\\cmidrule(lr){2-6}\\cmidrule(lr){7-7}",
        "$L$/$G$ & best & TraLO & $\\Delta$ & win & & $\\Delta$mac \\\\",
        "\\midrule",
    ]
    for dataset, sweep, dlab in specs:
        d = df[(df.sweep == sweep) & (df.dataset == dataset) & (df.model == "MobileNetV3")]
        if d.empty:
            continue
        tags = sorted(d.constraint_tag.unique(),
                      key=lambda t: (int(t.split("_")[0][1:]), int(t.split("G")[1])))
        # split G<L then G>L
        for blk, lo, hi in [("$G<L$ (global tighter)", True, False),
                            ("$G>L$ (local tighter)", False, True)]:
            sel = [t for t in tags
                   if (int(t.split("G")[1]) < int(t.split("_")[0][1:])) == lo
                   and (int(t.split("G")[1]) > int(t.split("_")[0][1:])) == hi]
            if not sel:
                continue
            rows, verdicts = [], []
            for tag in sel:
                sub = d[d.constraint_tag == tag]
                r = cell_stats(sub)
                if r is None:
                    continue
                L = tag.split("_")[0][1:]
                G = tag.split("G")[1]
                win = r.get("cc_win", 0)
                n = r.get("cc_n", 4)
                delta = r.get("cc_delta")
                verd = outcome(delta, win, n)
                verdicts.append(verd)
                rows.append(
                    f"{L}/{G} & {r.get('cc_best', float('nan')):.3f} & {r.get('cc_tralo', float('nan')):.3f} & "
                    f"{fmt_delta(delta, verd == 'win')} & {win}/{n} & {verd} & "
                    f"{fmt_delta(r.get('mac_delta'))} \\\\")
            if not rows:
                continue
            lines.append(f"\\multicolumn{{7}}{{l}}{{\\textit{{{dlab}, {blk}}}\\quad"
                         f"\\footnotesize {block_summary(verdicts)}}} \\\\")
            lines.extend(rows)
            lines.append("\\addlinespace[2pt]")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    with open(os.path.join(TABLES, "tab_granular_asym.tex"), "w") as f:
        f.write("\n".join(lines))
    return "tab_granular_asym.tex"


if __name__ == "__main__":
    df = pd.read_csv(CSV, low_memory=False)
    files = [
        sym_table(df, "tissuemnist", "TissueMNIST", "tab:gran_tissue"),
        sym_table(df, "dermmnist", "DermMNIST", "tab:gran_derm"),
        sym_table(df, "octmnist", "OctMNIST", "tab:gran_oct"),
        asym_table(df),
    ]
    print("wrote:", files)
    # sanity: print derm + oct L30 across backbones
    for ds in ["octmnist", "dermmnist"]:
        d = df[(df.sweep == "paper_final") & (df.dataset == ds)]
        print(f"\n{ds} L30_G30:")
        for mk, ml in BB_ORDER:
            r = cell_stats(d[(d.model == mk) & (d.constraint_tag == "L30_G30")])
            if r:
                print(f"  {ml:14s} cc Δ={r.get('cc_delta'):+.3f} win={r.get('cc_win')}/{r.get('cc_n')} "
                      f"macΔ={r.get('mac_delta'):+.3f}")
