"""Emit tab_alm_regime.tex: the ALM comparison over the WHOLE grid.

Blind review round 1, largest single deduction: the manuscript reported ALM on
the six OctMNIST tight-cap cells the B3 probe had run, and the expansion shows a
coherent region where ALM leads. Reporting only the winning band would be
selective even though it was not selective when written.

This table is the regime map: one row per (dataset, backbone), the mean paired
gap over that cell's nine caps, and the win/tie/loss split at the same +/-0.005
band every other comparison in the paper uses. The loss region gets its own
per-cap block rather than being averaged away.

Writes to tables_rev/ (revision-marked; tables/ is read by both manuscripts).
Run:  python paper/scripts/make_alm_regime_table.py
"""
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "tables_rev", "tab_alm_regime.tex")

import analyze_alm as A  # noqa: E402  (same directory)

BAND = 0.005
DSP = {"tissuemnist": "Tissue", "dermmnist": "Derm", "octmnist": "OctMNIST"}
BBP = {"MobileNetV3": "MobileNetV3", "RegNetY400MF": "RegNetY-400MF",
       "ViTB16": "ViT-B/16"}
ORDER = ["tissuemnist", "dermmnist", "octmnist"]


def wtl(g):
    return ((g > BAND).sum(), (g.abs() <= BAND).sum(), (g < -BAND).sum())


def main():
    df = A.load()
    df = df[df.model.isin(A.MAIN_BB)]
    c = A.cells(df)

    L = []
    L.append(r"% tab_alm_regime.tex -- TraLO vs ALM over the full grid.")
    L.append(r"% Generated by scripts/make_alm_regime_table.py. Do not hand-edit.")
    L.append(r"\begin{table}[t]\centering\small")
    L.append(r"\caption{{\color{blue}\textbf{TraLO versus the ALM dual across the whole grid,"
             r" not only the band we lead in.} Paired mean gap in cc-F1 (TraLO $-$ ALM) over"
             r" the nine symmetric caps of each dataset--backbone cell, seeds $1$--$4$;"
             r" W/T/L counts cells at the same $\pm0.005$ tie band used elsewhere. The"
             r" advantage is regime-specific in exactly the way the rest of the paper"
             r" describes: it concentrates where the cap binds hard, and OctMNIST"
             r" $\times$ MobileNetV3 at loose caps is a genuine loss region, itemised"
             r" below.}}")
    L.append(r"\label{tab:alm_regime}")
    L.append(r"\begin{tabular}{ll rr r}")
    L.append(r"\toprule")
    L.append(r"Dataset & Backbone & $\Delta$ cc-F1 & W/T/L & Caps \\")
    L.append(r"\midrule")

    for ds in ORDER:
        sub = c[c.dataset == ds]
        for i, bb in enumerate(A.MAIN_BB):
            s = sub[sub.model == bb]
            w, t, l = wtl(s.gap)
            lead = DSP[ds] if i == 0 else ""
            L.append(r"%s & %s & $%+.3f$ & %d/%d/%d & %d \\"
                     % (lead, BBP[bb], s.gap.mean(), w, t, l, len(s)))
        if ds != ORDER[-1]:
            L.append(r"\midrule")

    w, t, l = wtl(c.gap)
    L.append(r"\midrule")
    L.append(r"\multicolumn{2}{l}{\emph{All %d cells}} & $%+.3f$ & %d/%d/%d & %d \\"
             % (len(c), c.gap.mean(), w, t, l, len(c)))
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")

    lr = c[(c.dataset == "octmnist") & (c.model == "MobileNetV3")].copy()
    lr["cap"] = lr.constraint_tag.str.extract(r"L(\d+)").astype(int)
    lr = lr.sort_values("cap")
    L.append(r"\vspace{4pt}")
    L.append(r"{\color{blue}\footnotesize The loss region per cap"
             r" (OctMNIST $\times$ MobileNetV3, $\Delta$ cc-F1):}")
    L.append(r"\vspace{2pt}")
    L.append(r"{\color{blue}\footnotesize\begin{tabular}{l" + "r" * len(lr) + r"}")
    L.append(r"\toprule")
    L.append(r"Cap & " + " & ".join("L%d" % v for v in lr.cap) + r" \\")
    L.append(r"$\Delta$ cc-F1 & " + " & ".join("$%+.3f$" % v for v in lr.gap) + r" \\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}}")
    L.append(r"\end{table}")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", OUT)
    print("all cells %+.4f   W/T/L %d/%d/%d" % (c.gap.mean(), w, t, l))


if __name__ == "__main__":
    main()
