"""Do the four trained arms take DIFFERENT constraint steps? Bound it, do not guess.

THE ALGEBRA. Every trained arm in this project builds its constraint objective
out of the SAME per-constraint soft counts `S_j = sum_{i in G_j} p_ic`:

    fioretto_ldf   L = sum_j  lambda_j * S_j
    fioretto_alm   L = sum_j (lambda_j + mu * relu(r_j)) * S_j
    hounie_rcl     L = sum_j (lambda_j / N_j) * S_j
    tralo          L = sum_j  lambda_j * pen(S_j)

Differentiate. Every one of them is

    grad = sum_j  c_j * g_j ,      g_j = dS_j/dtheta ,      c_j >= 0

because lambda, mu, relu and `pen'` are all non-negative here. So all four arms
live in the CONVEX CONE generated by {g_j}, and under
`constraint_grad_mode: normalize` -- the recipe -- the magnitude is discarded
entirely. Two arms can therefore differ ONLY in where their weight vector points
inside that cone.

THE BOUND, and it is the point of this script. Normalise the generators. If the
MINIMUM pairwise cosine among them is gamma >= 0, then for any two non-negative
weightings a, b:

    <sum_j a_j ghat_j , sum_k b_k ghat_k>  >=  gamma * (sum a)(sum b)
    ||sum_j a_j ghat_j||^2 = sum_jk a_j a_k cos_jk  <=  (sum a)^2

    =>  cos(grad_A, grad_B)  >=  gamma                                   (*)

No dual rule, no hyperparameter, no schedule enters (*). It holds for the four
arms shipped here AND for every dual rule anyone could write on these counts.
If gamma is high the arms are the same step and the head-to-head measures the
weighting of a cone that has almost no width -- which is a structural fact about
the constraint family, not a defect in any one method.

WHAT IT IS COMPUTED ON. The head gradient is exact and needs no head weights:

    dS_j/dW_kd = sum_{i in G_j} p_ic (delta_ck - p_ik) f_id
    dS_j/db_k  = sum_{i in G_j} p_ic (delta_ck - p_ik)

so stored probabilities (`final_predictions_raw.csv`) and stored features
(`test_embeddings.npz`) determine it completely. That is the same head-only
scope `step_direction_probe` works in, and the same caveat applies: it bounds
what the constraint can do THROUGH THE LINEAR HEAD, where the effect is
exactly computable. The backbone is a further channel.

`--self-test` gates it in BOTH directions: a constructed set of generators that
really is collinear must report a tight bound, and a constructed set that is
spread must report a loose one. A bound that cannot come out loose has not been
shown to measure anything.
"""
import argparse
import glob
import itertools
import json
import os
import sys

import numpy as np
import pandas as pd

UNLIMITED = 1e10


def head_gradients(proba, feats, groups, capped, budgets_local, budgets_global):
    """One unit-normalised generator per ACTIVE constraint. Returns (names, G).

    `G` is (n_constraints, C*D + C). A constraint is included when its budget is
    finite; K == 0 counts, and on iwildcam half of them are 0.
    """
    n, C = proba.shape
    D = feats.shape[1]
    rows, names, meta = [], [], []

    def gen(mask, c):
        p = proba[mask]                      # (m, C)
        a = p[:, c]                          # (m,)
        coef = -a[:, None] * p               # (m, C)
        coef[:, c] += a                      # a(delta - p)
        W = coef.T @ feats[mask]             # (C, D)
        b = coef.sum(axis=0)                 # (C,)
        return np.concatenate([W.ravel(), b])

    for c in capped:
        K = budgets_global[c]
        if K < UNLIMITED:
            rows.append(gen(np.ones(n, dtype=bool), c))
            names.append("global/c%d/K=%d" % (c, K))
            meta.append((np.ones(n, dtype=bool), c, float(K)))
    for g in sorted(budgets_local):
        mask = (groups == g)
        if not mask.any():
            continue
        for c in capped:
            K = budgets_local[g][c]
            if K < UNLIMITED:
                rows.append(gen(mask, c))
                names.append("g%s/c%d/K=%d" % (g, c, K))
                meta.append((mask, c, float(K)))

    G = np.asarray(rows, dtype=np.float64)
    nrm = np.linalg.norm(G, axis=1, keepdims=True)
    keep = (nrm[:, 0] > 0)
    if not keep.all():
        names = [nm for nm, k in zip(names, keep) if k]
        meta = [m for m, k in zip(meta, keep) if k]
        G, nrm = G[keep], nrm[keep]
    return names, meta, G / nrm


def cone_bound(G):
    """(gamma, min_angle_deg, worst_pair). gamma is the minimum pairwise cosine."""
    Cm = G @ G.T
    m = Cm.shape[0]
    if m < 2:
        return 1.0, 0.0, (0, 0)
    iu = np.triu_indices(m, k=1)
    off = Cm[iu]
    k = int(np.argmin(off))
    gamma = float(off[k])
    ang = float(np.degrees(np.arccos(np.clip(gamma, -1.0, 1.0))))
    return gamma, ang, (int(iu[0][k]), int(iu[1][k]))


def arm_weights(soft, hard, K, sizes, epochs, cfg):
    """Each arm's non-negative weight vector PER EPOCH. Model held FIXED.

    The rules are the shipped ones, not paraphrases -- read against
    `tralo/train.py` (the ratchet is ADDITIVE and gated on the HARD count, and
    `rho_step` is DERIVED as `(rho_target - initial_rho)/constraint_epochs`),
    `fioretto_alm/train.py` (`mu_t` grows LINEARLY) and `fioretto_ldf/train.py`.
    An earlier version of this function guessed a multiplicative ratchet and
    rho_step=0.1; rho actually reaches 100, which changes which term of `pen'`
    dominates, so the guess was not a small error.

    Holding the model fixed isolates the WEIGHT trajectory, which is the only
    thing the arms disagree about. It is an approximation to a real run -- the
    counts move as training proceeds -- and it is the CHARITABLE direction for
    separation: with a frozen model no shared drift pulls the arms together.

    Returns {arm: (epochs, n_constraints) array}.
    """
    r = soft - K                       # signed soft residual
    viol = np.maximum(0.0, r)
    hard_viol = (hard > K)             # what the tralo ratchet actually reads
    out = {}

    # fioretto_ldf: lambda += step * relu(r); the backward at epoch t uses the
    # lambda written at the END of epoch t-1, hence the pre-update read.
    W = np.zeros((epochs, len(soft)))
    lam = np.full_like(soft, cfg["fioretto_lambda_init"])
    for t in range(epochs):
        W[t] = lam
        lam = lam + cfg["fioretto_step_size"] * viol
    out["fioretto_ldf"] = W

    # fioretto_alm: weight = lambda + mu_t * relu(r), mu_t linear in the epoch.
    W = np.zeros((epochs, len(soft)))
    lam = np.full_like(soft, cfg["fioretto_lambda_init"])
    for t in range(epochs):
        mu_t = cfg["alm_mu0"] + cfg["alm_mu_step"] * t
        W[t] = lam + mu_t * viol
        lam = np.maximum(0.0, lam + cfg["alm_eta"] * r)
    out["fioretto_alm"] = W

    # hounie_rcl: the resilient dual, and the objective divides by N_j.
    W = np.zeros((epochs, len(soft)))
    lam = np.zeros_like(soft)
    u = np.zeros_like(soft)
    N = np.maximum(1.0, sizes)
    mean_l = r / N
    for t in range(epochs):
        W[t] = lam / N
        lam = np.maximum(0.0, lam + cfg["hounie_eta_lambda"] * (mean_l - u))
        u = np.maximum(0.0, u + cfg["hounie_eta_u"] * (lam - 2.0 * cfg["hounie_alpha"] * u))
    out["hounie_rcl"] = W

    # tralo: weight = lambda * pen'(S). lambda ratchets ADDITIVELY while the
    # HARD count violates; pen' is the bounded shape's derivative, and rho ramps
    # from initial_rho to rho_target across the phase.
    W = np.zeros((epochs, len(soft)))
    lam = np.full_like(soft, cfg["tralo_lambda_init"])
    rho = cfg["tralo_initial_rho"]
    rho_step = (cfg["tralo_rho_target"] - cfg["tralo_initial_rho"]) / max(epochs, 1)
    scale = np.maximum(K, 1.0)
    E = viol
    e = E / scale
    for t in range(epochs):
        dpen = (scale / (E + scale) ** 2
                + rho * 2.0 * e / (scale * (1.0 + e ** 2) ** 2))
        W[t] = lam * dpen
        lam = np.where(hard_viol, lam + cfg["tralo_lambda_step"], lam)
        rho = rho + rho_step
    out["tralo"] = W
    return out


# The one arm pair whose cosine this instrument CANNOT measure: a fixed-state
# replay forces it to 1.0. See the note printed by `report`. FRAMEWORK 2(z28).
FORCED_PAIR = {"fioretto_alm", "fioretto_ldf"}


def report(names, G, soft, hard, K, sizes, epochs, cfg, w=sys.stdout.write):
    """Print the cone bound and the ARM-vs-ARM angles, per epoch."""
    gamma, ang, (i, j) = cone_bound(G)
    w("  constraints: %d   (K==0: %d)\n" % (len(names), int((K == 0).sum())))
    w("  MIN pairwise cosine among generators = %+.4f  (%.1f deg)\n"
      % (gamma, ang))
    w("    worst pair: %s  vs  %s\n" % (names[i], names[j]))
    if gamma >= 0:
        w("  => cone is ACUTE: ANY two non-negative weightings sit within %.1f deg\n"
          % ang)
    else:
        w("  => cone is NOT acute, so the bound (*) is vacuous here. The per-arm\n"
          "     angles below are the measurement; the cone does not bound them.\n")

    ws = arm_weights(soft, hard, K, sizes, epochs, cfg)
    arms = sorted(ws)
    D = {}
    for a in arms:
        V = ws[a] @ G                                  # (epochs, dim)
        nv = np.linalg.norm(V, axis=1, keepdims=True)
        D[a] = np.divide(V, nv, out=np.zeros_like(V), where=nv > 0)
        last = ws[a][-1]
        tot = last.sum()
        k = int(np.argmax(last))
        w("  %-14s final: %.3f of its weight on %s\n"
          % (a, (last[k] / tot if tot > 0 else 0.0), names[k]))

    w("  arm-vs-arm cosine of the constraint-gradient DIRECTION:\n")
    w("      %-14s %-14s %8s %8s %8s\n" % ("armA", "armB", "ep1", "ep29", "min"))
    worst = 1.0
    for a, b in itertools.combinations(arms, 2):
        c = np.einsum("ij,ij->i", D[a], D[b])
        c = c[np.isfinite(c)]
        if not len(c):
            continue
        worst = min(worst, float(c.min()))
        w("      %-14s %-14s %+8.4f %+8.4f %+8.4f%s\n"
          % (a, b, c[0], c[-1], c.min(),
             "   <- FORCED" if {a, b} == FORCED_PAIR else ""))
    if FORCED_PAIR.issubset(set(arms)):
        w("  THE `FORCED` ROW IS NOT A MEASUREMENT. This probe holds the model\n")
        w("  still, so `r` is CONSTANT over the 29 replayed updates, and under a\n")
        w("  constant `r` both fioretto arms build a positive multiple of relu(r):\n")
        w("  LDF `T*step*relu(r)`, ALM `(T*eta + mu_T)*relu(r)`, with\n")
        w("  `alm_eta == fioretto_step_size == 0.005` and both lambda_init 0. The\n")
        w("  cosine is 1 by ALGEBRA; no state could return anything else. They\n")
        w("  differ only under >= 2 constraints with DIFFERENT violation HISTORIES\n")
        w("  -- ALM's raw-residual projection DECAYS a multiplier LDF's positive\n")
        w("  part HOLDS -- and searched over trajectories they reach 90.0 deg on\n")
        w("  disjoint supports. Use the AS-DEPLOYED comparison for this pair.\n")
        w("  FRAMEWORK 2(z28).\n")
    return gamma, worst


def _frac(pct, cls, classes):
    """`cap_fraction_for`, duplicated deliberately: this probe must run in a
    campaign worktree pinned at an older commit, where importing
    src.training.constraints can fail on version skew. The semantics are gated
    against the real budgets by `--check-budgets`."""
    if isinstance(pct, (int, float)):
        return float(pct)
    return float(list(pct)[list(classes).index(int(cls))])


def budgets_from_labels(df, cfg, capped):
    """Re-derive the integer budgets the trainer used, from labels + cap policy.

    `config.json` stores only the FRACTIONS; K is computed at runtime as
    `round(true_count * fraction)` with numpy's banker's rounding. Reproducing
    it here rather than reading it means the probe cannot silently disagree with
    the trainer about what was capped -- and `_round_to_K`'s .5 convention does
    occur at these cap levels.
    """
    local_pct, global_pct = cfg["constraint"][0], cfg["constraint"][1]
    ncls = cfg["dataset_config"]["num_classes"]
    y, g = df["True_Label"].to_numpy(), df["Group_ID"].to_numpy()

    gcon = [UNLIMITED] * ncls
    for c in capped:
        gcon[c] = int(np.round((y == c).sum() * _frac(global_pct, c, capped)))
    lcon = {}
    for grp in np.unique(g):
        row = [UNLIMITED] * ncls
        m = (g == grp)
        for c in capped:
            row[c] = int(np.round((y[m] == c).sum() * _frac(local_pct, c, capped)))
        lcon[grp] = row
    return gcon, lcon


def load_run(run_dir):
    cfg = json.load(open(os.path.join(run_dir, "config.json")))
    npz = np.load(os.path.join(run_dir, "test_embeddings.npz"))
    feats = npz["features"].astype(np.float64)
    df = pd.read_csv(os.path.join(run_dir, "final_predictions_raw.csv"))
    pcols = sorted([c for c in df.columns if c.startswith("Prob_Class")],
                   key=lambda s: int(s.rsplit("_", 1)[1]))
    proba = df[pcols].to_numpy(dtype=np.float64)
    groups = df["Group_ID"].to_numpy()
    if len(proba) != len(feats):
        raise SystemExit("predictions (%d) and features (%d) disagree in %s"
                         % (len(proba), len(feats), run_dir))
    # The features and the probabilities must come from the SAME model state or
    # every gradient here is a chimera, and the two are written by different
    # calls. `log p` is a valid logit vector (softmax is shift-invariant), so if
    # one forward pass produced both there is a W with `log p = f W^T + const`.
    # Fit it and compare BACK IN PROBABILITY SPACE.
    #
    # NOT in log space, which is where this check was first written and where it
    # is useless: the stored probabilities reach 7.8e-14, and a float32 rounding
    # at that magnitude is a full unit of log-odds. The log-space residual read
    # 1.45 on a run whose probabilities round-trip to 7.2e-06 -- the check
    # rejected a perfectly consistent pair. Probability space weights each entry
    # by how much it can actually move a count, which is what the gradient reads.
    lp = np.log(np.clip(proba, 1e-30, 1.0))
    lp = lp - lp.mean(axis=1, keepdims=True)
    A = np.concatenate([feats, np.ones((len(feats), 1))], axis=1)
    sol, *_ = np.linalg.lstsq(A, lp, rcond=None)
    zh = A @ sol
    zh = zh - zh.max(axis=1, keepdims=True)
    ph = np.exp(zh)
    ph /= ph.sum(axis=1, keepdims=True)
    resid = float(np.abs(ph - proba).max())
    return cfg, proba, feats, groups, df, resid


def self_test(w=sys.stdout.write):
    """Both directions. A bound that cannot come out LOOSE measures nothing."""
    ok = True

    def check(good, label):
        nonlocal ok
        w("  %-4s %s\n" % ("PASS" if good else "FAIL", label))
        ok = ok and good

    rng = np.random.default_rng(0)

    base = rng.normal(size=64)
    base /= np.linalg.norm(base)
    G = base + 0.01 * rng.normal(size=(6, 64))
    G /= np.linalg.norm(G, axis=1, keepdims=True)
    gamma, ang, _ = cone_bound(G)
    check(gamma > 0.99, "near-collinear generators give a TIGHT bound (gamma=%.4f)" % gamma)

    a = rng.normal(size=(6, 64))
    a /= np.linalg.norm(a, axis=1, keepdims=True)
    g2, ang2, _ = cone_bound(a)
    check(g2 < 0.5, "LIVENESS: independent generators give a LOOSE bound (gamma=%.4f)" % g2)

    # (*) itself: sample non-negative weightings and confirm none beats gamma.
    Gc = base + 0.15 * rng.normal(size=(8, 64))
    Gc /= np.linalg.norm(Gc, axis=1, keepdims=True)
    gam, _, _ = cone_bound(Gc)
    worst = 1.0
    for _ in range(4000):
        u = rng.random(8) @ Gc
        v = rng.random(8) @ Gc
        worst = min(worst, float(u @ v / (np.linalg.norm(u) * np.linalg.norm(v))))
    check(gam >= 0 and worst >= gam - 1e-12,
          "bound (*) holds over 4000 random weightings (gamma=%.4f, worst=%.4f)"
          % (gam, worst))

    # arm_weights must be able to SEPARATE arms, or it proves nothing downstream.
    soft = np.array([400.0, 50.0, 300.0])
    hard = np.array([380.0, 45.0, 290.0])
    K = np.array([100.0, 40.0, 0.0])
    sizes = np.array([2943.0, 400.0, 400.0])
    cfg = DEFAULT_CFG.copy()
    ws = {a: V[-1] for a, V in arm_weights(soft, hard, K, sizes, 29, cfg).items()}
    sh = {a: v / v.sum() for a, v in ws.items() if v.sum() > 0}
    spread = max(np.abs(sh[x] - sh[y]).max()
                 for x, y in itertools.combinations(sorted(sh), 2))
    check(spread > 0.05,
          "LIVENESS: the four dual rules produce DIFFERENT weight shares (max diff %.3f)"
          % spread)

    # THE BLIND SPOT, gated in both directions. Under a CONSTANT residual --
    # which is all a fixed-state replay can express -- the two fioretto arms
    # are forced parallel by algebra, so a cosine of 1 here is not evidence.
    fa, fl = ws["fioretto_alm"], ws["fioretto_ldf"]
    cos_fixed = float(fa @ fl / (np.linalg.norm(fa) * np.linalg.norm(fl)))
    check(abs(cos_fixed - 1.0) < 1e-9,
          "FORCED: at a fixed state fioretto_alm and _ldf are parallel by "
          "algebra (cos=%.9f), so this probe cannot measure that pair"
          % cos_fixed)

    # and the NEGATIVE CONTROL: a history where one constraint goes slack
    # DOES separate them, so the identity above is a limitation of the replay
    # and not a property of the two methods. FRAMEWORK 2(z28).
    lam_l = np.zeros(2)
    lam_a = np.zeros(2)
    W_l = W_a = None
    for t in range(29):
        r = np.array([40.0, 12.0 if t < 15 else -20.0])
        v = np.maximum(0.0, r)
        W_l, W_a = lam_l.copy(), lam_a + (cfg["alm_mu0"]
                                          + cfg["alm_mu_step"] * t) * v
        lam_l = lam_l + cfg["fioretto_step_size"] * v
        lam_a = np.maximum(0.0, lam_a + cfg["alm_eta"] * r)
    cos_hist = float(W_a @ W_l / (np.linalg.norm(W_a) * np.linalg.norm(W_l)))
    check(cos_hist < 0.999,
          "NEGATIVE CONTROL: a constraint going SLACK mid-phase separates them "
          "(cos=%.6f), so the forced 1.0 above is the replay, not the methods"
          % cos_hist)

    w("\nSELF-TEST %s\n" % ("PASSED" if ok else "FAILED"))
    return 0 if ok else 1


DEFAULT_CFG = {
    # configs/protocol.yml, read 2026-09-02. Every value is the shipped one.
    "fioretto_step_size": 0.005, "fioretto_lambda_init": 0.0,
    "alm_eta": 0.005, "alm_mu0": 0.01, "alm_mu_step": 0.01,
    "hounie_eta_lambda": 0.1, "hounie_eta_u": 0.1, "hounie_alpha": 1.0,
    "tralo_lambda_init": 0.01, "tralo_lambda_step": 0.05,
    "tralo_initial_rho": 0.5, "tralo_rho_target": 100.0,
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--glob", help="run directories holding test_embeddings.npz")
    ap.add_argument("--epochs", type=int, default=29)
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()

    if a.self_test:
        return self_test()
    if not a.glob:
        ap.error("--glob is required (or use --self-test)")

    runs = sorted(glob.glob(a.glob))
    if not runs:
        raise SystemExit("no runs matched %r" % a.glob)

    gammas, worsts = [], []
    for rd in runs:
        if not os.path.exists(os.path.join(rd, "test_embeddings.npz")):
            continue
        cfg, proba, feats, groups, df, resid = load_run(rd)
        capped = [int(c) for c in cfg["dataset_config"]["constrained_class"]]
        gcon, lcon = budgets_from_labels(df, cfg, capped)
        print("\n== %s" % rd)
        print("  head-consistency residual (max |p_hat - p|): %.2e" % resid)
        if resid > 1e-3:
            print("  ** features and probabilities are NOT one forward pass; "
                  "gradients below would be a chimera. SKIPPING. **")
            continue

        names, meta, G = head_gradients(proba, feats, groups, capped, lcon, gcon)
        pred = df["Predicted_Label"].to_numpy()
        soft = np.array([float(proba[m, c].sum()) for m, c, _ in meta])
        hard = np.array([float((pred[m] == c).sum()) for m, c, _ in meta])
        K = np.array([k for _, _, k in meta])
        sizes = np.array([float(m.sum()) for m, _, _ in meta])
        g, wst = report(names, G, soft, hard, K, sizes, a.epochs, DEFAULT_CFG)
        gammas.append(g)
        worsts.append(wst)

    if gammas:
        print("\n== SUMMARY over %d runs" % len(gammas))
        print("  gamma (cone bound):        min %+.6f  median %+.6f  max %+.6f"
              % (min(gammas), float(np.median(gammas)), max(gammas)))
        print("  worst ARM-vs-ARM cosine:   min %+.6f  median %+.6f  max %+.6f"
              % (min(worsts), float(np.median(worsts)), max(worsts)))
        print("  -> worst arm-vs-arm angle: %.3f deg (median %.3f)"
              % (np.degrees(np.arccos(np.clip(min(worsts), -1, 1))),
                 np.degrees(np.arccos(np.clip(float(np.median(worsts)), -1, 1)))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
