from .mobilenetv3 import MobileNetV3Classifier
from .convnext import ConvNeXtTinyClassifier
from .mobilenetv2 import MobileNetV2Classifier
from .shufflenet import ShuffleNetV2Classifier
from .regnet import RegNetY400MFClassifier
from .mobilevit_s import MobileViTSClassifier
from .efficientformer_l1 import EfficientFormerL1Classifier
from .mnasnet13 import MNASNet13Classifier
from .convnext_pico import ConvNeXtPicoClassifier
