"""Generate the two backbone-breadth supplement tables from the shipped corpus:
  tab_backbone_generality.tex -- cc-F1 vs best trained dual (tie on Tissue/Derm, win on Oct)
  tab_deploy_backbone.tex      -- macro-F1 vs best post-hoc clipper (positive everywhere)
across the 3 main-grid backbones + MobileNetV2, symmetric caps.

Self-contained (inlines the canonical filter, like make_octmnist_fig.py): seed-mean WITHIN
each (dataset,model,cap,method) cell, per-seed-best envelope baseline, paired gap; the cell
verdict counts caps with a +-0.005 tie band. No pooling across cells/backbones/datasets.

Run:  python final_AAAI_PAPER/scripts/make_backbone_tables.py
"""
import os
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CSV = os.path.join(ROOT, "final_AAAI_PAPER", "data", "corpus", "corpus_final.csv")
TAB = os.path.join(ROOT, "final_AAAI_PAPER", "tables")

CANON = {"tissuemnist": (4, "synth_group"), "dermmnist": (4, "loc_group"),
         "octmnist": (2, "synth_group")}
BLOCK = {"smoke_reorg", "warmup1_probe", "warmup_ablation", "extra_robustness"}
KEY = ["dataset", "model", "constraint_tag", "method", "seed"]
BB = [("MobileNetV3", "MobileNetV3"), ("RegNetY400MF", "RegNetY-400MF"),
      ("ViTB16", "ViT-B/16"), ("MobileNetV2", "MobileNetV2")]
DS = [("tissuemnist", "Tissue"), ("dermmnist", "Derm"), ("octmnist", "OctMNIST")]
EPS = 0.005


def load():
    df = pd.read_csv(CSV, low_memory=False)
    df = df[df.warmup_epochs == 50]
    df = df[~df.sweep.isin(BLOCK)]
    df = df[df.apply(lambda r: CANON.get(r.dataset) == (r.constrained_class, r.group_column), axis=1)]
    df["_pri"] = (df.sweep != "paper_final").astype(int)
    df = df.sort_values("_pri").drop_duplicates(subset=KEY, keep="first")
    lg = df.constraint_tag.str.extract(r"L(\d+)_G(\d+)").astype(int)
    df["L"], df["G"] = lg[0].values, lg[1].values
    return df[df.L == df.G]


def cell_gaps(df, metric, bases):
    """per (dataset,model): per-cap records vs the per-seed-best baseline. Each record is
    (mean_gap, n_clear_pos, n_clear_neg, n_seeds). Win rule (paper Sec 5.2): mean gap >= +eps
    AND at least half the seeds clear +eps; loss is the mirror image."""
    out = {}
    for (ds, mdl), g in df.groupby(["dataset", "model"]):
        recs = []
        for tag, gg in g.groupby("constraint_tag"):
            piv = gg.pivot_table(index="seed", columns="method", values=metric)
            have = [b for b in bases if b in piv]
            if "tralo" not in piv or not have:
                continue
            best = piv[have].max(axis=1)
            d = (piv["tralo"] - best).dropna()
            if len(d) >= 3:
                recs.append((float(d.mean()), int((d >= EPS).sum()),
                             int((d <= -EPS).sum()), len(d)))
        out[(ds, mdl)] = recs
    return out


def wtl(recs):
    w = t = l = 0
    for mean, cpos, cneg, n in recs:
        half = (n + 1) // 2
        if mean >= EPS and cpos >= half:
            w += 1
        elif mean <= -EPS and cneg >= half:
            l += 1
        else:
            t += 1
    return w, t, l


def rows_tex(gp):
    lines = []
    for mdl, mlab in BB:
        cells = []
        for ds, _ in DS:
            recs = gp.get((ds, mdl), [])
            if recs:
                w, t, l = wtl(recs)
                mean = np.mean([r[0] for r in recs])
                cells.append(f"${mean:+.3f}$ {{\\scriptsize {w}/{t}/{l}}}")
            else:
                cells.append("--")
        lines.append(f"{mlab:14s} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines)


def write(path, body):
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    print("WROTE", path)


df = load()
A = cell_gaps(df, "cc_f1", ["fioretto_ldf", "hounie_rcl"])
B = cell_gaps(df, "f1_macro", ["heuristic", "danits_lp"])

write(os.path.join(TAB, "tab_backbone_generality.tex"), r"""% GENERATED by scripts/make_backbone_tables.py -- do not hand-edit.
% cc-F1 gap of TraLO over the best trained dual (per-seed best of Fioretto/Hounie), mean over
% the symmetric caps per (dataset,backbone); w/t/l counts caps at a +-0.005 tie band. Seed-mean
% within a cell, then averaged over caps -- no cross-cell/backbone/dataset pooling.
\begin{table}[t]\centering\small
\setlength{\tabcolsep}{4.5pt}
\caption{\textbf{The constrained-class picture is backbone-general.} Mean paired
constrained-class-F1 gap of TraLO over the best constraint-trained baseline (per-seed best of
Fioretto-LDF/Hounie-RCL), averaged over the symmetric caps for each dataset--backbone cell;
{\scriptsize win/tie/loss} counts the caps (a win needs the mean gap and at least half the seeds
to clear $+0.005$; loss is the mirror). Across all four backbones---the three in the main grid
plus MobileNetV2---TissueMNIST and DermMNIST show no systematic constrained-class advantage
(per-backbone means within $\pm0.003$, mostly ties), while OctMNIST is a positive margin on every
backbone. The honest tie and the OctMNIST win are both properties of the regime, not of one architecture.}
\label{tab:bbgen}
\begin{tabular}{l rrr}
\toprule
Backbone & Tissue & Derm & OctMNIST \\
\midrule
""" + rows_tex(A) + r"""
\bottomrule
\end{tabular}
\end{table}
""")

write(os.path.join(TAB, "tab_deploy_backbone.tex"), r"""% GENERATED by scripts/make_backbone_tables.py -- do not hand-edit.
% macro-F1 gap of TraLO over the best post-hoc clipper (per-seed best of Heuristic/Shifman-LP),
% mean over the symmetric caps per (dataset,backbone); w/t/l counts caps at a +-0.005 tie band.
\begin{table}[t]\centering\small
\setlength{\tabcolsep}{4.5pt}
\caption{\textbf{TraLO's macro-F1 advantage over post-hoc clipping is backbone- and
dataset-general.} Mean paired macro-F1 gap of TraLO over the best post-hoc clipper (per-seed
best of Heuristic/Shifman-LP), averaged over the symmetric caps for each dataset--backbone cell;
{\scriptsize win/tie/loss} counts the caps. The mean gain is positive in every cell, largest on
TissueMNIST; it also holds under asymmetric caps (App.~\ref{app:regime}).}
\label{tab:deploybb}
\begin{tabular}{l rrr}
\toprule
Backbone & Tissue & Derm & OctMNIST \\
\midrule
""" + rows_tex(B) + r"""
\bottomrule
\end{tabular}
\end{table}
""")

print("\nTable A (cc-F1 vs trained):")
print(rows_tex(A))
print("\nTable B (macro-F1 vs clipper):")
print(rows_tex(B))
