"""Task #5: replace the pooled regime table (S3) with FULLY GRANULAR per-cell tables.

One row per (dataset, backbone, cap) -- averaging over the 4 seeds ONLY, never pooling
across backbones or caps. Two paired comparisons per row:
  * cc-F1  vs the best constraint-TRAINED baseline (per-seed max of Fioretto/Hounie),
  * macro-F1 vs the best POST-HOC clipper   (per-seed max of Heuristic/Shifman).
Gaps are paired by seed then averaged; 'win' is the seed-winrate (k/4).

Emits, into final_AAAI_PAPER/tables/:
  tab_granular_tissue.tex, tab_granular_derm.tex, tab_granular_oct.tex  (symmetric grid)
  tab_granular_asym.tex   (MobileNetV3 asymmetric caps: DermMNIST + TissueMNIST)

Symmetric data = sweep 'paper_final' (3 bb x 9 caps). Asymmetric = the dedicated
MobileNetV3 sweeps in the corpus (derm=paperv2_phase2, tissue=g2_asym_tissue_aider).

Run:  python final_AAAI_PAPER/scripts/make_granular_tables.py
"""
import os
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV = os.path.join(ROOT, "data", "corpus", "corpus_final.csv")
TABLES = os.path.join(ROOT, "tables")
DUALS = ["fioretto_ldf", "hounie_rcl"]
CLIP = ["heuristic", "danits_lp"]
SYM_TAGS = [f"L{p}0_G{p}0" for p in range(1, 10)]  # L10..L90
BB_ORDER = [("MobileNetV3", "MobileNetV3"), ("RegNetY400MF", "RegNetY-400MF"),
            ("ViTB16", "ViT-B/16")]


def cell_stats(sub):
    """sub = rows for one (dataset, model, cap). Returns paired cc + macro stats."""
    cc = sub.pivot_table(index="seed", columns="method", values="cc_f1")
    mac = sub.pivot_table(index="seed", columns="method", values="f1_macro")
    have_tr = "tralo" in cc and cc["tralo"].notna().any()
    if not have_tr:
        return None
    r = {}
    # cc-F1 vs best trained dual
    duals = [d for d in DUALS if d in cc]
    if duals:
        best_tr = cc[duals].max(axis=1)
        pair = pd.concat([cc["tralo"], best_tr], axis=1, keys=["tralo", "best"]).dropna()
        r["cc_best"] = pair["best"].mean()
        r["cc_tralo"] = pair["tralo"].mean()
        r["cc_delta"] = (pair["tralo"] - pair["best"]).mean()
        r["cc_win"] = int((pair["tralo"] > pair["best"]).sum())
        r["cc_n"] = len(pair)
    # macro-F1 vs best clipper
    clips = [c for c in CLIP if c in mac]
    if clips:
        best_cl = mac[clips].max(axis=1)
        pair = pd.concat([mac["tralo"], best_cl], axis=1, keys=["tralo", "best"]).dropna()
        r["mac_delta"] = (pair["tralo"] - pair["best"]).mean()
    return r


def fmt_delta(x, bold_win=False):
    if x is None or np.isnan(x):
        return "--"
    s = f"{x:+.3f}"
    return f"\\textbf{{{s}}}" if bold_win else s


def sym_table(df, dataset, title, label):
    d = df[(df.sweep == "paper_final") & (df.dataset == dataset)]
    lines = [
        "% AUTO-GENERATED by scripts/make_granular_tables.py -- do not hand-edit.",
        "\\begin{table}[t]\\centering\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        f"\\caption{{\\textbf{{{title}: per-cell constrained-class and overall F1.}} "
        "One row per (backbone, cap), mean over seeds $1$--$4$. cc-F1 columns compare TraLO "
        "to the best constraint-trained baseline (per-seed best of Fioretto-LDF/Hounie-RCL, "
        "paired); \\emph{win} is the seed-winrate. $\\Delta$mac is TraLO minus the best "
        "post-hoc clipper on macro-F1. \\textbf{Bold} $\\Delta$ marks a paired win "
        "($\\Delta\\ge0.005$ on $\\ge3/4$ seeds).}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{l rrr c r}",
        "\\toprule",
        " & \\multicolumn{4}{c}{cc-F1 vs.\\ best trained} & macro \\\\",
        "\\cmidrule(lr){2-5}\\cmidrule(lr){6-6}",
        "Cap & best & TraLO & $\\Delta$ & win & $\\Delta$mac \\\\",
        "\\midrule",
    ]
    for mkey, mlab in BB_ORDER:
        dm = d[d.model == mkey]
        if dm.empty:
            continue
        lines.append(f"\\multicolumn{{6}}{{l}}{{\\textit{{{mlab}}}}} \\\\")
        for tag in SYM_TAGS:
            sub = dm[dm.constraint_tag == tag]
            if sub.empty:
                continue
            r = cell_stats(sub)
            if r is None:
                continue
            cap = tag.split("_")[0]
            win = r.get("cc_win", 0)
            n = r.get("cc_n", 4)
            is_win = (r.get("cc_delta", 0) >= 0.005) and (win >= 3)
            lines.append(
                f"{cap} & {r.get('cc_best', float('nan')):.3f} & {r.get('cc_tralo', float('nan')):.3f} & "
                f"{fmt_delta(r.get('cc_delta'), is_win)} & {win}/{n} & {fmt_delta(r.get('mac_delta'))} \\\\")
        lines.append("\\addlinespace[2pt]")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    out = os.path.join(TABLES, label.replace("tab:", "tab_") + ".tex")
    fname = {"tab:gran_tissue": "tab_granular_tissue.tex",
             "tab:gran_derm": "tab_granular_derm.tex",
             "tab:gran_oct": "tab_granular_oct.tex"}[label]
    with open(os.path.join(TABLES, fname), "w") as f:
        f.write("\n".join(lines))
    return fname


def asym_table(df):
    specs = [("dermmnist", "paperv2_phase2", "DermMNIST"),
             ("tissuemnist", "g2_asym_tissue_aider", "TissueMNIST")]
    lines = [
        "% AUTO-GENERATED by scripts/make_granular_tables.py -- do not hand-edit.",
        "\\begin{table}[t]\\centering\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\caption{\\textbf{Asymmetric caps (MobileNetV3): per-cell F1.} Global cap $L$ and "
        "group cap $G$ set independently; one row per cap pair, mean over seeds $1$--$4$. "
        "Columns as in Table~\\ref{tab:gran_derm}. The global-tighter ($G{<}L$) block is where "
        "the single preliminary cc-F1 win sits; $\\Delta$mac stays positive throughout.}",
        "\\label{tab:gran_asym}",
        "\\begin{tabular}{l rrr c r}",
        "\\toprule",
        " & \\multicolumn{4}{c}{cc-F1 vs.\\ best trained} & macro \\\\",
        "\\cmidrule(lr){2-5}\\cmidrule(lr){6-6}",
        "Cap ($L$/$G$) & best & TraLO & $\\Delta$ & win & $\\Delta$mac \\\\",
        "\\midrule",
    ]
    for dataset, sweep, dlab in specs:
        d = df[(df.sweep == sweep) & (df.dataset == dataset) & (df.model == "MobileNetV3")]
        if d.empty:
            continue
        tags = sorted(d.constraint_tag.unique(),
                      key=lambda t: (int(t.split("_")[0][1:]), int(t.split("G")[1])))
        # split G<L then G>L
        for blk, lo, hi in [("$G<L$ (global tighter)", True, False),
                            ("$G>L$ (local tighter)", False, True)]:
            sel = [t for t in tags
                   if (int(t.split("G")[1]) < int(t.split("_")[0][1:])) == lo
                   and (int(t.split("G")[1]) > int(t.split("_")[0][1:])) == hi]
            if not sel:
                continue
            lines.append(f"\\multicolumn{{6}}{{l}}{{\\textit{{{dlab}, {blk}}}}} \\\\")
            for tag in sel:
                sub = d[d.constraint_tag == tag]
                r = cell_stats(sub)
                if r is None:
                    continue
                L = tag.split("_")[0][1:]
                G = tag.split("G")[1]
                win = r.get("cc_win", 0)
                n = r.get("cc_n", 4)
                is_win = (r.get("cc_delta", 0) >= 0.005) and (win >= 3)
                lines.append(
                    f"{L}/{G} & {r.get('cc_best', float('nan')):.3f} & {r.get('cc_tralo', float('nan')):.3f} & "
                    f"{fmt_delta(r.get('cc_delta'), is_win)} & {win}/{n} & {fmt_delta(r.get('mac_delta'))} \\\\")
            lines.append("\\addlinespace[2pt]")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    with open(os.path.join(TABLES, "tab_granular_asym.tex"), "w") as f:
        f.write("\n".join(lines))
    return "tab_granular_asym.tex"


if __name__ == "__main__":
    df = pd.read_csv(CSV, low_memory=False)
    files = [
        sym_table(df, "tissuemnist", "TissueMNIST", "tab:gran_tissue"),
        sym_table(df, "dermmnist", "DermMNIST", "tab:gran_derm"),
        sym_table(df, "octmnist", "OctMNIST", "tab:gran_oct"),
        asym_table(df),
    ]
    print("wrote:", files)
    # sanity: print derm + oct L30 across backbones
    for ds in ["octmnist", "dermmnist"]:
        d = df[(df.sweep == "paper_final") & (df.dataset == ds)]
        print(f"\n{ds} L30_G30:")
        for mk, ml in BB_ORDER:
            r = cell_stats(d[(d.model == mk) & (d.constraint_tag == "L30_G30")])
            if r:
                print(f"  {ml:14s} cc Δ={r.get('cc_delta'):+.3f} win={r.get('cc_win')}/{r.get('cc_n')} "
                      f"macΔ={r.get('mac_delta'):+.3f}")
